name: tenk10k-causal-paper
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  # Python packages
  - python>=3.8
  - pandas>=1.5.0
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - scanpy>=1.8.0
  - torch>=1.10.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  
  # R and R packages
  - r-base>=4.0.0
  - r-tidyverse>=1.3.0
  - r-data.table>=1.14.0
  - r-arrow>=8.0.0
  - r-patchwork>=1.1.0
  - r-ggplot2>=3.3.0
  - r-dplyr>=1.0.0
  - r-scales>=1.2.0
  - r-paletteer>=1.4.0
  - r-ragg>=1.2.0
  - r-readxl>=1.4.0
  - r-writexl>=1.4.0
  - r-broom>=1.0.0
  - r-fs>=1.5.0
  - r-glue>=1.6.0
  - r-ggrepel>=0.9.0
  - r-ggridges>=0.5.0
  - r-formattable>=0.2.0
  - r-ggnewscale>=0.4.0
  - r-geomtextpath>=0.1.0
  - r-ggforce>=0.3.0
  - r-qvalue>=2.24.0
  - r-rtracklayer>=1.52.0
  
  # Bioconductor packages (if needed)
  - bioconductor-qvalue
  - bioconductor-rtracklayer
  
  # System tools
  - snakemake>=7.0.0
  - mamba>=0.24.0
  
  # Additional tools for workflow
  - plink>=1.90
  - bedtools>=2.30.0
  
  # Optional: Jupyter for interactive analysis
  - jupyter>=1.0.0
  - notebook>=6.0.0
  
  # pip dependencies
  - pip
  - pip:
    - scdrs>=1.0.0
    - gget>=0.4.0